### ISSUE TITLE
Can You Teach Me about Adapter?

### ISSUE THREAD

**Issue by Zerglrisk** [vmihalachi/turbo-editor#110]
Hi, I'm student from Korean. i studying android 2 month ago. i saw this 2 weeks ago and studied. but i don't understand about adapter. can you teach me about Adapter? i'm sorry my rudeness

**Comment by vmihalachi** [comment]
No I'm sorry, there are many tutorials online however that you can check! :)

**Comment by Zerglrisk** [comment]
Thank you. i will master that :)

**Comment by z3t0** [comment]
@Zerglrisk Please read http://www.edureka.co/blog/what-are-adapters-in-android/ 
Also feel free to email me if you need more resources or have more questions at zetoslab@gmail.com

**Comment by Zerglrisk** [comment]
@z3t0 i owe you one, i will must contact you. thx.

**Comment by z3t0** [comment]
@Zerglrisk no problem, happy to help
