### ISSUE TITLE
Does not build with JDK 8, please consider merging my fix.

### ISSUE THREAD

**Issue by thebunnyrules** [vmihalachi/turbo-editor#160]
Hi, the build.gradle scripts for app and app-pro crash during dexing on JDK 8. I've tried running gradle with JDK 7 but either gradle or the SDK are refusing to run with it. I've found a very simple fix where a slight modification to the build.gradle scripts makes the project build with JDK 8. 

I've made a pull request for the fix: https://github.com/vmihalachi/turbo-editor/pull/159

**Comment by vmihalachi** [comment]
Merged, thanks!
