### ISSUE TITLE
Line number sometimes are not refreshed

### ISSUE THREAD

**Issue by mlmarenchino** [vmihalachi/turbo-editor#48]
Hi,

If I enable the "Syntax Highlight", the every time I scroll a file, the line numbers and the syntax is refreshed. But if I disable that option, sometimes the line numbers are not refreshed. Here is a screenshot of that situation:

![line_number](https://cloud.githubusercontent.com/assets/5825788/4861837/fba436a4-6106-11e4-9328-ba3f15f0ca0f.png)

**Comment by vmihalachi** [comment]
Hi, I should have fixed this issue in the last update (1.15)!
