### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by biosan** [vmihalachi/turbo-editor#57]
Add `.markdown` and `.md` file association and possible some type of syntax highlighting

**Comment by biosan** [comment]
I tried JotterPad X and it works right. When I open a `.md` file from dropbox app or file manager it shows up as a default app.

**Comment by vmihalachi** [comment]
Tried with dropbox and now it works!

**Comment by JanoschDeurer** [comment]
I get the same problem in Seafile, it says, that it can not find any app for this kind of file.
