### ISSUE TITLE
Link to Github repo in About dialog broken

### ISSUE THREAD

**Issue by flasheater** [vmihalachi/turbo-editor#60]
When clicking on the Github icon in the info dialog, I get a 404 because it is trying to reach "TurboEditor" repo instead of "turbo-editor".

**Comment by vmihalachi** [comment]
Hi, what version of the app do you have?

**Comment by flasheater** [comment]
Version 1.12

**Comment by vmihalachi** [comment]
I have fixed it in the newer version. Don't know why fdroid doesn't update the apk.
