### ISSUE TITLE
Cursor Position jumps to top of viewport

### ISSUE THREAD

**Issue by flasheater** [vmihalachi/turbo-editor#61]
When scrolling in the editor, the cursor always jumps upon touch release to the top of the current viewport of the scroll view. 

Tested on Nexus 5 with CM11.

**Comment by jlintott** [comment]
This also occurs on version 1.15 on my Samsung Galaxy Tab S using the Type S cover

**Comment by jlintott** [comment]
Upon more use it only seems to happen when editing a css file

**Comment by vmihalachi** [comment]
Does it still happen?

**Comment by jlintott** [comment]
Yes, I was using it earlier today and having the same issue. I am working with the latest version 1.16. I am only having the problem in css files while working outside curly brackets. If I pause while typing the cursor jumps to the top of the page.

**Comment by jlintott** [comment]
Just tested on my nexus 5 as well. Same issue occurs. It only occurs with syntax highlighting turned on. I think it is caused by the highlighting refresh

**Comment by vmihalachi** [comment]
Does it happen only with css files?

**Comment by jlintott** [comment]
As far as I have noticed. Yes

**Comment by vmihalachi** [comment]
Unfortunately I can't reproduce it. Can you send me a css file that doesn't work properly? (by email if you can maskyngames@gmail.com)

**Comment by vmihalachi** [comment]
Fixed in the new release! :)
