### ISSUE TITLE
Can not open file from other app (opera download)

### ISSUE THREAD

**Issue by LancelotC** [vmihalachi/turbo-editor#65]
Hi

Can not open file from other app(opera download)

I guess all extension open with
is missing,

When I download a file (blabla.testme) with opera and click open, turbo editor is not in the list..

I hope above helps, I like Turbo Editor a lot :)

**Comment by vmihalachi** [comment]
Does it work now with version 1.18.2?

**Comment by LancelotC** [comment]
Thanks a lot , Yes I can open blabla.test from opera now  :) :) :)

Testing more, I can not open .script , Turbo Editor is not in list to open .script
ps: only WPS Office, Mobo Player, B1 File Manager, Extract shown in list when .script selected

ps:
In Windows terms, I am after
HKEY_CLASSES_ROOT\*\shell\TurboEditor
ex:
HKEY_CLASSES_ROOT\*\shell\Notepad\Command    notepad "%1"

So I can open TurboEditor on files I know txt easly ;)

**Comment by vmihalachi** [comment]
Did understand the second part sorry ahahaha :smile: 
Anyway I will add other extension including .script and see if it helps!
