### ISSUE TITLE
Korean charactors not integrated into syllables

### ISSUE THREAD

**Issue by cachai** [vmihalachi/turbo-editor#66]
I'm not sure other Korean users have had the same problem,
but Korean alphabets are supposed to form a syllable to make sense.
Like 곰 means 'bear' in Korean but ㄱㅗㅁ means nothing but scribble.
Unfortunately that's exactly turbo editor is doing when typing Korean.
I think your app is great but help me use Korean, too.
(I haven't had a problem with the other text editor apps, so..)

**Comment by vmihalachi** [comment]
Hi, does this behavior persist in the last version (1.15.1)?
