### ISSUE TITLE
Each edit and save adds blank line to end of file

### ISSUE THREAD

**Issue by dbolton** [vmihalachi/turbo-editor#67]
Steps to reproduce
1. Open a text file and make an edit.
2. Save and close the file
3. Reopen the file

Expected behavior: The reopened file should be the same as when you saved it.

Actual behavior: The reopened file has an extra line break at the end

**Comment by vmihalachi** [comment]
Hi, does this behavior persist in the last version (1.15.1)?

**Comment by dbolton** [comment]
I was using 1.12 (the latest version on F-droid).
