### ISSUE TITLE
Copy, Paste, Cut Options - Blank

### ISSUE THREAD

**Issue by Romtoc** [vmihalachi/turbo-editor#69]
Whenever I select a text by double tapping, the options such as copy, paste etc are all blank.

My phone is the Xperia SP and I'm using version 1.15.2 of this app. 

Here is a screenshot of the issue I'm facing: http://postimg.org/image/5zzjha0eb/

**Comment by vmihalachi** [comment]
It's strange because O do not have this problem on Lollipop. What Android version do you have?

**Comment by Romtoc** [comment]
Android 4.3 Jelly Bean. The previous version 1.14 never had this issue.

**Comment by vmihalachi** [comment]
Okey, it seems like a bug of the updated support library. Anyway I fixed this issue, so wait for the next release :)
