### ISSUE TITLE
Force Close On Replace All

### ISSUE THREAD

**Issue by Romtoc** [vmihalachi/turbo-editor#79]
The first time I used it, it worked. The next time I tried and times after that it keeps crashing. I tried clearing data and that didn't fix it unfortunately.
![screenshot_2015-03-19-14-42-44](https://cloud.githubusercontent.com/assets/6082642/6727972/219b68b6-ce4c-11e4-9304-d128d922b6f3.png)

**Comment by vmihalachi** [comment]
Can you try to see if it is the particular text of file that causes the issue?

**Comment by Romtoc** [comment]
Its actually pretty much every file I try, any text. I'm not even sure why it won't work anymore.

**Comment by vmihalachi** [comment]
Can you copy the report here?

**Comment by Romtoc** [comment]
Unfortunately I can't but I've sent an error report, hopefully you've got it. I also hope this helps: http://i.imgur.com/1lGPtk7.png

**Comment by Romtoc** [comment]
This issue seems to be fixed with version 1.19. Thank you!

**Comment by vmihalachi** [comment]
Well, believe it or not an user today on xda has said that the app crashes after using replace all ahahah

**Comment by Romtoc** [comment]
How strange...lol. Have you found out what's causing this? To me it seems to be fixed with the latest version.

**Comment by vmihalachi** [comment]
No, not really, I hope he was referring to the previous version 1.18 but I don't know..
