### ISSUE TITLE
Can't create new file

### ISSUE THREAD

**Issue by kudlav** [vmihalachi/turbo-editor#82]
I'm using HTC One S
Android 4.1.1
with HTC Sense 4+

After last update when I:
1) open app (1.18.1)
2) open left menu
3) choose "New file"
4) error
![2015-03-22_11-25-19](https://cloud.githubusercontent.com/assets/11516259/6768963/39b2b5d0-d086-11e4-8f54-949bdfbe9830.png)

OR:
when:
1) open app (1.18.1)
2) open left menu
3) choose "Open a file"
4) tap on the +
5) choose "File"
6) write name, ok
7) no file was created and when I something write to this no existing file, it is saved to some previously opened file

**Comment by vmihalachi** [comment]
Hope that the new update 1.18.2 will fix this issue. I tested it on android 4.0 so it should work. 
Thanks for the feedback help!
