### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by JavaJens** [vmihalachi/turbo-editor#85]
I don't know if I should open this here or over at F-Droid, but the recent builds have failed due to a wrong version of the built tools.
Thanks for this great app!

**Comment by vmihalachi** [comment]
Hi, what does that mean? I can build correctly the app.

**Comment by JavaJens** [comment]
Yes, but the F-Doird builtbot can't. That's why the latest version in F-Droid is 1.12
I don't know much about F-Droid to be more specific though, sorry.
Here is the link to the log: https://f-droid.org/wiki/page/com.maskyn.fileeditorpro/lastbuild_46
https://f-droid.org/wiki/page/com.maskyn.fileeditorpro

**Comment by vmihalachi** [comment]
Maybe now it works with this new update because the build tools version is now '22.0.1'. 
Sincerely I can't understand what is the issue and what should I change.

**Comment by JavaJens** [comment]
I saw that there are several other apps that failed due to the same error.
I also read that they've upgraded the build tools to version 22, so hopefully this should resolve itself.

I guess there is nothing you can do, as it is an error with F-Droid. I just didn't know how well you are connected with F-Droid that is why I opened up this issue here. Thanks again!
