### ISSUE TITLE
Support opening files of Terminal IDE

### ISSUE THREAD

**Issue by eshepelyuk** [vmihalachi/turbo-editor#86]
[Terminal IDE](http://www.spartacusrex.com/terminalide.htm) stores files under  `/data/data/com.spartacusrex.spartacuside/files/projects`. When opening files from editor one could navigate to that folder, but can not open any project folder inside it, so unable to open any file. The same time when using any file manager with root access and using `Open With Turbo Editor` - those files are opened succesfully.

**Comment by vmihalachi** [comment]
Hi, what version are you using?
Turbo Editor is able to view files that require root access, did you grant it?

**Comment by eshepelyuk** [comment]
1. Version is 1.19
2. `Turbo Editor` can display those files when called from other program, e.g. `Total Commander` via `Open With` menu item or similar
3. I can not open `Terminal IDE` files directly from `Turbo Editor`, because file open dialog (non Storage Access Framework) does not allow me to navigate to project folder.
* `Terminal IDE` uses `/data/data/com.spartacusrex.spartacuside/files/projects` as root folder for source code
* I got a project have cloned to that folder, named `myCoolProj`
* when trying to open file from `Turbo Editor` file open dialog - I can navigate to `/data/data/com.spartacusrex.spartacuside/files/projects` and I am able to see `myCoolProj` folder.
* but when clicking on `myCoolProj` within file open dialog - nothing happens, i.e. `Turbo Editor` doesn't display its content and stays on the same level of file system
* although I can navigate to my source code from file manager (`Total Commander` in my case) and open the source code files in `Turbo Editor` using `Open With` menu item

**Comment by eshepelyuk** [comment]
Do you need any other details about the bug ?

**Comment by vmihalachi** [comment]
No, the description is clear enough. The only problem is that Terminal IDE crashes on my device everytime I click "Terminal IDE".

**Comment by eshepelyuk** [comment]
Could I help you to debug on my device ? 
Setup some custom version with debug info, error report or smth else ?

**Comment by eshepelyuk** [comment]
It works. Thank you !
