### ISSUE TITLE
Keyboard covers last lines when it opened

### ISSUE THREAD

**Issue by code-museum** [vmihalachi/turbo-editor#88]

**Comment by vmihalachi** [comment]
Do you mean that you cant scroll to see the last lines?
Would you please post a screenshot?

**Comment by code-museum** [comment]
![Uploading Screenshot_2015-03-29-11-48-26.png . . .]()

**Comment by vmihalachi** [comment]
I cant see anything, also are you using the last version? (1.19)

**Comment by code-museum** [comment]
sorry i'll try to add an image later with my pc.

**Comment by code-museum** [comment]
Checked again. The text is hidden by the accesaory. The keyboard is ok.
I'm using 1.19.

**Comment by vmihalachi** [comment]
Ok, now I understand what you mean, the cursor goes under the accessory view, right?

**Comment by code-museum** [comment]
Yeah, that's it.










On Sun, Mar 29, 2015 at 6:12 AM -0700, "Vlad Mihalachi" <notifications@github.com> wrote:
Ok, now I understand what you mean, the cursor goes under the accessory view, right?

---

**Comment by vmihalachi** [comment]
Ok, the fix will be available in the next release!

**Comment by code-museum** [comment]
Cool, thank you










On Sun, Mar 29, 2015 at 6:24 AM -0700, "Vlad Mihalachi" <notifications@github.com> wrote:
Ok, the fix will be available in the next release!

---
