### ISSUE TITLE
 Update code on GitHub

### ISSUE THREAD

**Issue by demoneaux** [vmihalachi/turbo-editor#99]
The app has been updated, but the code has not been for two months.

**Comment by Theodus2009** [comment]
It looks like the code is lagging behind published application again. Could you please push the latest code to GitHub @vmihalachi? I'm happy to look in to issue #107 which I also experienced on my phone, but an app built from the latest published codebase behaves much more strangely with an external keyboard than the latest version on Google Play, so I can't recreate the issue.

**Comment by rugk** [comment]
This also explains why the Freud FDroid version is still 1.19 while the Google play version is v2.4.

But it seems the developer does not like open source anymore as his other app - turbo client - [as not open source at all] (https://github.com/vmihalachi/turbo-client-issue-tracker/issues/5).
